### ISSUE TITLE
ps vita port?

### ISSUE THREAD

**Issue by Toni-d-e-v** [PSP-Archive/PSP-MAME4ALL#1]

**Comment by ptnnx** [comment]
Seriously, PS Vita port?
But,
We all work on the homebrews for PSP related preservation. Maybe I don't think anyone would want to make it.
If you want to play PSP-Mame4all then you can do it a using adrenaline Vita [PSP Emulator for Vita].

[CFW 6.61 Adrenaline for the PSP Emulator for Vita](https://github.com/TheOfficialFloW/Adrenaline)

It can run all PSP homebrews.

**Comment by pierrelouys** [comment]
Honestly you'll get much better MAME emulation on Vita than you'd ever get with Mame4All by just using Retroarch.

**Comment by Toni-d-e-v** [comment]
@Rdx-Official Adrenaline does not use vita resources but emulated one. So performance will be same

**Comment by ptnnx** [comment]
> @Rdx-Official Adrenaline does not use vita resources but emulated one. So performance will be same

Vita port is difficult to Make a PSPMAME4All
I think you will go on vita dev discord anyone Helping you may be.?
